const names = [
    "John",
    "Thomas",
    "Michael",
    "William",
    "David",
    "Richard",
    "Joseph",
    "Charles",
    "Daniel",
    "Matthew",
    "Anthony",
    "Mark",
    "Christopher",
    "Joshua",
    "Andrew",
    "Brian",
    "Kevin",
    "Steven",
    "Edward",
    "George",
    "Paul",
    "Peter",
    "James",
    "Robert",
    "Benjamin",
    "Henry",
    "Alexander",
    "Nicholas",
    "Samuel",
    "Jacob",
    "Jonathan",
    "Aaron",
    "Ryan",
    "Kyle",
    "Adam",
    "Justin",
    "Scott",
    "Brandon",
    "Eric",
    "Gary",
];

export default function generateRandomName() {
    const randomIndex = Math.floor(Math.random() * names.length);
    return names[randomIndex];
}
